version: '3.9'
services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend/data.xlsx:/app/data.xlsx
    frontend:
        build: ./frontend
        ports:
            - "8501:8501"
        depends_on:
            - backend
    nginx:
        image: nginx:latest 
        ports:
            - "80:80"
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - frontend
            - backend