version: '3.8'
services:
    backend:
        image: dushyanth00/backend:${IMAGE_TAG}
        ports:
            - "8000:8000"
    frontend:
        image: dushyanth00/frontend:${IMAGE_TAG}
        ports:
            - "8501:8501"
        depends_on:
            - backend
 